version: '2.2'
services:
  apps:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    image: agenda_maker:latest
    runtime: nvidia
    ports:
      - "6006:6006"  # Tensorboard用ポート
      - "1234:1234"  # Tensorboard用ポート
      - "8888:8888"  # JupyterLab用ポート
    shm_size: 32gb
    command: ["/bin/bash"]