
# 実行するタスク設定
tasks:
  wav_preprocess_is: False
  annotation_is: False
  transcription_is: True
  segmentation_is: True
  summarization_is: True

# 共通部分のパラメータ
common:
  seed: 42

preprocess:
  cut_time:
    start_time: 0 # 音声データの初めてn秒カット
    end_time: 5 # 音声データの終わりn秒カット
  silence_cut:
    min_silence_len: 500 #n秒以上無音なら分割
    silence_thresh: -60 #ndBFS以下で無音と判定
    keep_silence: 50 #分割後Nmsは無音を残す
  
model: 

  # 文章分割のパラメータ
  # sementic segmentation のパラメータ
  segmentation:
    max_segmented_text: 8000 # 1セグメントの最大文字数
    segment_num: 4 # 最大セグメント数
    semantic_segmentation:
      model_type: "pkshatech/GLuCoSE-base-ja" # SentenceTransformerのモデルタイプ
      max_segment_text: 8000 # 1セグメントの最大文字数
      threshold_step: 0.01 # 
      threshold: 0.6
    # text tillingのパラメータ
    text_tiling:
      model_name: model_text_tilling
      w: 15 #Pseudosentence size
      k: 10 #Size (in sentences) of the block used in the block comparison method
      smoothing_width: 2 #The width of the window used by the smoothing method
      smoothing_rounds: 10 #The number of smoothing passes

  whisperx:
  # 文字起こしのパラメータ
    whisper:
      model_name: model_whisper
      model_type: large-v2
      compute_type: float32
      batch_size: 2 # 1batch 4gb位
    # 話者分離のパラメータ
    diarization:
      min_speakers: 1 # 発話している最小人数
      max_speakers: 4 # 発話している最大人数
